# Generated by Django 5.2.7 on 2025-10-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=200)),
                ('data_emissao', models.DateField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
            ],
        ),
    ]
